# Generated by Django 3.0.5 on 2020-06-14 05:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account_Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=8)),
                ('Friends', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='True', max_length=200), size=100)),
                ('User', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='App.Account')),
            ],
        ),
    ]
