# Generated by Django 3.0.5 on 2020-06-16 08:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=8)),
                ('Friends', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=100)),
            ],
        ),
    ]
